// Palabras prohibidas (nada que ver con tu vivero)
export const PALABRAS_PROHIBIDAS = [
    "sexo",
    "política",
    "religión",
    "insulto",
    "violencia"
];

// Temáticas permitidas (solo respondemos a esto)
export const TEMATICAS_PERMITIDAS = [
    "árbol",
    "frutales",
    "arbustos",
    "plantas de interior",
    "plantas de exterior",
    "paisajismo",
    "geranio",
    "cuidados",
    "plantas de sombra",
    "flores",
    "rastrillo",
    "azada",
    "tijera corta hoja",
    "aspersor",
    "barre hojas",
    "barrera antihormigas",
    "kit de jardineria",
    "hormiguicida",
    "fuente",
    "decoración",
    "planta",
    "suculenta",
    "cactus",
    "jardín",
    "riego",
    "sustrato",
    "maceta",
    "abono",
    "fertilizante",
    "comprar",
    "pedido",
    "envío",
    "cuidado",
    "calathea",  
    "ficus",     
    "poto",
    "pothus",
    "sanseviera", 
    "monstera",  
    "alocasia",  
    "bamboo",    
    "codiaeum",  
    "gerbera",  
    "cinta",
    "lazos de amor",
    "planta araña",
    "helecho",
    "lithops",
    "crasa",
    "echeveria",
    "macetas gota",
    "macetas rotomoldeadas",
    "fuente de agua buda",
    "fuente de agua",
    "kit de herramientas",
    "kit huertero",
    "gerbera",
    "lavanda",
    "hortensia",
    "azalea",
    "petunias",
    "gerbera",
    "tomillo",
    "rosas",
    "girasoles",
    "fuchsias",
    "magnolia",
    "cilantro",
    "tomate",
    "fresno",
    "eucalyptus",
    "zinnia",
    "dracaena",
    "sedum",
    "echeveria",
    "opuntia",
    "agave",
    "liquido de algas",
    "fertilizante granular",
    "guano de murciélago",
    "humus de lombriz",
    "fertilizante para orquídeas",
    "fertilizante foliar",
    "fertilizante para rosas",
    "fertilizante líquido para tomate",
    "fertilizante 10-10-10",
    "fertilizante a base de calcio",
    "bioestimulante para plantas",
    "abono fosfatado",
    "fertilizante para césped",
    "tierra",
    "fuente de agua buda para decoracion de patios",
    "fuente de agua  para decoracion de patios",
    "Kit de herramientas pala,rastrillo,barre hojas",
];

// Respuestas amables si la pregunta no entra en la temática
export const respuestasAmables = [
    "Perdón 🌱, solo puedo ayudarte con consultas sobre plantas, jardinería o compras en el vivero El Ceibo. ¿Te gustaría saber más sobre alguna planta específica?",
    "Mi conocimiento está enfocado en cuidados de plantas y productos del vivero 🌿. Si necesitas recomendaciones, ¡estoy aquí para ayudarte!",
    "Lo siento, pero puedo asistirte únicamente en temas de jardinería y nuestro vivero. ¿Puedo ayudarte con alguna planta en particular?"
];
